networks:
  connectNetwork:
services:
  nginx:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:80
    depends_on:
      - api
    volumes:
      - ../client/build/:/usr/share/nginx/html
      - ../client/default.conf:/etc/nginx/conf.d/default.conf
  mssql:
    container_name: Library
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "XuanTruong1810"
    ports:
      - "1433:1433"
    volumes:
      - my-volume:/var/opt/mssql
    expose:
      - 1433
    networks:
      - connectNetwork
  api:
    build:
      context: ../Server
      dockerfile: Dockerfile
    ports:
      - 5076:5076
    environment:
      - DB_HOST=localhost
      - DB_PORT=1433
      - SA_PASSWORD=XuanTruong1810
    depends_on:
      - mssql
    networks:
      - connectNetwork

volumes:
  my-volume:
